title: Pixel pet
hero_image: images/banner.png
description: Make a walking pixel pet with your Raspberry Pi and a Sense HAT
original_url: https://www.raspberrypi.org/learning/pixel-pet/
theme: red
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: builder, design-1, programming-2, phys-comp-1, manufacture-0, community-0
interests:
technologies:
steps:
  - title: Introduction
  - title: What you will need
  - title: Draw your pixel pet
  - title: Setting your colours
  - title: Representing your pet
  - title: Animate your pet
  - title: Create a walking function
  - title: Shake to activate
  - title: What next?
